version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
        - optional
