language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pytest==5.4.3 pytest-cov coveralls
  - pip install -r requirements.txt
  - pip install .[all]

script:
  - pytest --cov=pvanalytics --cov-config=.coveragerc --cov-report term-missing pvanalytics --runslow

after_success:
  - coveralls
